trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - main
      - dev
      - feature/*
      - hotfix/*

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo Hello, tags!
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), contains(variables['Build.SourceBranchName'], 'refs/tags/v'))
  displayName: 'Only tagas'